name: Sincronizar Fork

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta automáticamente todos los días a la medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sincronización Nativa de Fork
        uses: tgymnich/fork-sync-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master       # La rama del repositorio original (razvanzeces)
          head: master       # Tu rama destino en tu fork
          owner: razvanzeces # Dueño original
