name: Sincronizar Fork

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta automáticamente todos los días a la medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sincronizar con el repositorio original
        uses: actions/checkout@v4
        with:
          repository: razvanzeces/flowstation
          ref: master # ← CAMBIADO AQUÍ (El original usa master)
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Actualizar mi Fork
        run: |
          # Sincroniza el contenido en la rama master de tu propio fork
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@://github.com{{ github.repository }}.git HEAD:master --force
